services:
  # API Gateway
  traefik:
    image: "traefik:v3.0"
    container_name: traefik-gateway
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # пyбличный HTTP
      - "8080:8080" # для Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - minor-network

  # NATS
  nats:
    image: nats:2.10-alpine
    container_name: nats
    restart: unless-stopped
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222" #Порт для подключения клиентов
      - "8222:8222" #Порт для мониторинга
    volumes:
      - ./volumes/nats_data:/data
    networks:
      - minor-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8222/varz"]
      interval: 10s
      timeout: 5s
      retries: 3

  # REDIS
  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis_data:/data
    networks:
      - minor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # CASSANDRA
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    restart: unless-stopped
    environment:
      CASSANDRA_CLUSTER_NAME: "MessangerCluster"
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
    ports:
      - "9042:9042"
    volumes:
      - ./volumes/cassandra_data:/var/lib/cassandra
    networks:
      - minor-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "cqlsh -u cassandra -p cassandra -e 'describe cluster' || exit 1",
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  message-cassandra-migrator:
    build:
      context: ../..
      dockerfile: minor/backend/services/message_service/migrator.Dockerfile
    container_name: message-service-migrator
    environment:
      - CASSANDRA_HOSTS=cassandra-db
    networks:
      - minor-network
    depends_on:
      cassandra:
        condition: service_healthy

  # POSTGRES
  auth-postgres:
    image: postgres:15-alpine
    container_name: auth-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: discord_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: discord_core
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data/auth:/var/lib/postgresql/data
    networks:
      - minor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discord_admin -d discord_core"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-postgres:
    image: postgres:15-alpine
    container_name: user-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service_master_key
      POSTGRES_DB: user_service
    ports:
      - "5484:5432"
    volumes:
      - ./volumes/postgres_data/user:/var/lib/postgresql/data
    networks:
      - minor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-migrator:
    image: migrate/migrate:v4.17.1
    container_name: user-migrator
    volumes:
      - ../backend/services/user_service/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://user_service:user_service_master_key@user-postgres:5432/user_service?sslmode=disable
      - up
    networks:
      - minor-network
    depends_on:
      user-postgres:
        condition: service_healthy

  community-postgres:
    image: postgres:15-alpine
    container_name: community-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: community_service
      POSTGRES_PASSWORD: community_service_master_key
      POSTGRES_DB: community_service
    ports:
      - "5482:5432"
    volumes:
      - ./volumes/postgres_data/community:/var/lib/postgresql/data
    networks:
      - minor-network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U community_service -d community_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  community-migrator:
    image: migrate/migrate:v4.17.1
    container_name: community-migrator
    volumes:
      - ../backend/services/community_service/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://community_service:community_service_master_key@community-postgres:5432/community_service?sslmode=disable
      - up
    networks:
      - minor-network
    depends_on:
      community-postgres:
        condition: service_healthy

  # SERVICES
  community_service:
    build:
      context: ../..
      dockerfile: minor/backend/services/community_service/Dockerfile
    container_name: community-service
    ports:
      - "8082:8082"
      - "50082:50082"
    environment:
      - ENV=local
      - HTTP_SERVER_ADDRESS=0.0.0.0:8082
      - GRPC_SERVER_ADDRESS=0.0.0.0:50082
      - NUTS_URL=nats://nats:4222
      - POSTGRES_HOST=community-postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=community_service
      - POSTGRES_PASSWORD=community_service_master_key
      - POSTGRES_DATABASE=community_service
    # env_file:
    #   - ../backend/services/community_service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.community.rule=PathPrefix(`/api/v1/servers`) || PathPrefix(`/api/v1/channels`)"
      - "traefik.http.routers.community.entrypoints=web"
      - "traefik.http.routers.community.middlewares=auth-verify"
      - "traefik.http.services.community.loadbalancer.server.port=8082"
    networks:
      - minor-network
    depends_on:
      community-postgres:
        condition: service_healthy

  message_service:
    build:
      context: ../..
      dockerfile: minor/backend/services/message_service/server.Dockerfile
    container_name: message-service
    ports:
      - "8083:8083"
    environment:
      - ENV=local
      - HTTP_SERVER_ADDRESS=0.0.0.0:8083
      - CASSANDRA_HOST=cassandra-db
      - CASSANDRA_KEYSPACE=chat
      - REDIS_URL=redis://redis-cache:6379
      - NATS_URL=nats://nats:4222
      - GRPC_CLIENT_USER_TARGET=user-service:50084
      - GRPC_CLIENT_COMMUNITY_TARGET=community-service:50082
    # env_file:
    #   - ../backend/services/message_service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.messages.rule=PathPrefix(`/api/v1/messages`)"
      - "traefik.http.routers.messages.entrypoints=web"
      - "traefik.http.routers.messages.middlewares=auth-verify"
      - "traefik.http.services.messages.loadbalancer.server.port=8083"
    networks:
      - minor-network
    depends_on:
      cassandra:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy

  user_service:
    build:
      context: ../..
      dockerfile: minor/backend/services/user_service/Dockerfile
    container_name: user-service
    ports:
      - "8084:8084"
      - "50084:50084"
    environment:
      - ENV=local
      - HTTP_SERVER_ADDRESS=0.0.0.0:8084
      - GRPC_SERVER_ADDRESS=0.0.0.0:50084
      - NUTS_URL=nats://nats:4222
      - POSTGRES_HOST=user-postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user_service
      - POSTGRES_PASSWORD=user_service_master_key
      - POSTGRES_DATABASE=user_service
    # env_file:
    #   - ../backend/services/user_service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=PathPrefix(`/api/v1/users`)"
      - "traefik.http.routers.users.entrypoints=web"
      - "traefik.http.routers.users.middlewares=auth-verify"
      - "traefik.http.services.users.loadbalancer.server.port=8084"
    networks:
      - minor-network
    depends_on:
      user-postgres:
        condition: service_healthy

  presence_service:
    build:
      context: ../..
      dockerfile: minor/backend/services/presence_service/Dockerfile
    container_name: presence-service
    ports:
      - "50086:50086"
    environment:
      - ENV=local
      - GRPC_SERVER_ADDRESS=0.0.0.0:50086
      - REDIS_URL=redis://redis-cache:6379
      - NUTS_URL=nats://nats:4222
    # env_file:
    #   - ../backend/services/presence_service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.presence.rule=PathPrefix(`/api/v1/presence`)"
      - "traefik.http.routers.presence.entrypoints=web"
      - "traefik.http.routers.presence.middlewares=auth-verify"
      - "traefik.http.services.presence.loadbalancer.server.port=8086"
    networks:
      - minor-network
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy

# NETWORKS
networks:
  minor-network:
    driver: bridge
