app:
  name: "auth-service"
  version: "1.0.0"
  env: "dev"

http:
    port: 8081
    timeout: 10s
    idle_timeout: 60s
    cors:
        allowed_origins: ["http://localhost:3000", "http://localhost:80"]

grpc:
  port: 50051

postgres:
    host: "auth-postgres"
    port: 5451
    user: "minor-user"
    password: "minor-password"
    db_name: "minor-auth"
    sslmode: "disable" #enable
    max_pool_size: 20

redis:
  host: "redis" 
  port: 6379
  password: ""
  db: 0

nats:
  url: "nats://localhost:4222"
  stream_name: "AUTH_STREAM"

auth:
  jwt_secret: "secret-word"
  access_token_ttl: "15m"    
  refresh_token_ttl: "720h"