app:
  name: "notification-service"
  env: "dev"
  version: "1.0.0"

nats:
  url: "nats://nats:4222"
  stream: "CHAT_STREAM"
  subject: "chat.message.>"
  durable_name: "notification_service_worker"

clients:
  presence_service:
    address: "presence_service:50051"
    timeout: "2s"
  user_service:
    address: "user_service:50051"
    timeout: "2s"

smtp:
  host: "smtp.gmail.com"
  port: 587
  user: "stepan41kr@gmail.com"
  password: "${SMTP_PASS}" 
  from: "Minor Messenger <stepan41kr@gmail.com>"

logger:
  level: "info"
  format: "json"